### ISSUE TITLE
come key list and come key balance stopped working for me.

### ISSUE THREAD

**Issue by rayzor72** [agicommies/communex#21]
It was working fine, then it stopped minutes later.
Here is the error I receive.

                                                                                                  │
│ /usr/lib/python3.10/json/__init__.py:339 in loads                                                │
│                                                                                                  │
│   336 │   │   │   │   │   │   │   │     s, 0)                                                    │
│   337 │   else:                                                                                  │
│   338 │   │   if not isinstance(s, (bytes, bytearray)):                                          │
│ ❱ 339 │   │   │   raise TypeError(f'the JSON object must be str, bytes or bytearray, '           │
│   340 │   │   │   │   │   │   │   f'not {s.__class__.__name__}')                                 │
│   341 │   │   s = s.decode(detect_encoding(s), 'surrogatepass')                                  │
│   342                                                                         

TypeError: the JSON object must be str, bytes or bytearray, not dict

**Comment by rayzor72** [comment]
I'm not a coder so I need it explained to me like I'm 7yr old...

**Comment by Supremesource** [comment]
> I'm not a coder so I need it explained to me like I'm 7yr old...

Hey we know about the issue and are working on fixing it. We will release an update later today on PyPi

**Comment by steinerkelvin** [comment]
@rayzor72 Can you inspect the files on `~/.commune/key/` and check if they are consistent or if there is something weird there?

**Comment by rayzor72** [comment]
am I doing this right?

usr@server1:~/commune$ ~/.commune/key/
-bash: /home/usr/.commune/key/: Is a directory

**Comment by rayzor72** [comment]
how do I open it?

**Comment by rayzor72** [comment]
> @rayzor72 Can you inspect the files on `~/.commune/key/` and check if they are consistent or if there is something weird there?

Is that the command to access it?
Here's what comes up:

usr@server1:~/commune$ ~/.commune/key/
-bash: /home/usr/.commune/key/: Is a directory

**Comment by rayzor72** [comment]
Thank you.  What is PyPi and how to I update once it's ready?

**Comment by steinerkelvin** [comment]
PyPI is just the default repository of Python packages. If you installed it through `pip` you should be able to do just:

```sh
pip install --upgrade communex
``` 

once it's published.
