### ISSUE TITLE
Permission denied when creating keys

### ISSUE THREAD

**Issue by Supremesource** [agicommies/communex#4]
If you run into `[Errno 13] Permission denied: '/home/$USER/.commune/key'` 
when creating or manipulating your keys. 
Make sure to run the following: 
```sh
sudo chown -R $USER:$USER ~/.commune
```

**Comment by steinerkelvin** [comment]
Do you know what causes this folder to be created with the wrong owner?

Perhaps it's when the user runs the a docker image that mounts a volume on `~/.commune` before any other operation that uses the folder then the Docker daemon creates all parent folders with `root:root` owner?

Do `commune` have any other operations that usually run as root/sudo and write to `~/.commune`?
