### ISSUE TITLE
comx --testnet balance run-faucet key - error: ValueError: Pallet 'FaucetModule' not found

### ISSUE THREAD

**Issue by dariusz-bzowka-chain-insight** [agicommies/communex#78]
i try to run faucet: 
comx --testnet balance run-faucet <my_key>

error message: 
ValueError: Pallet 'FaucetModule' not found

**Comment by dariusz-bzowka-chain-insight** [comment]
root@vmi2075799:/# comx --testnet balance run-faucet key_name
Using node: wss://testnet-commune-api-node-0.communeai.net
Running with 24 cores.
Finished
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /usr/local/lib/python3.10/dist-packages/communex/cli/balance.py:258 in run_faucet                │
│                                                                                                  │
│   255 │   │   │   │   "work": solution.seal,                                                     │
│   256 │   │   │   │   "key": resolved_key.ss58_address,                                          │
│   257 │   │   │   }                                                                              │
│ ❱ 258 │   │   │   client.compose_call("faucet", params=params, unsigned=True,                    │
│   259 │   │   │   │   │   │   │   │   module="FaucetModule", key=resolved_key.ss58_address)  #   │
│   260                                                                                            │
│   261                                                                                            │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │              _ = 0                                                                           │ │
│ │         client = <communex.client.CommuneClient object at 0x7f8fafc18d60>                    │ │
│ │        context = CustomCtx(                                                                  │ │
│ │                  │   ctx=<click.core.Context object at 0x7f8fafc0b820>,                      │ │
│ │                  │   console=<console width=194 ColorSystem.TRUECOLOR>,                      │ │
│ │                  │   console_err=<console width=194 ColorSystem.TRUECOLOR>,                  │ │
│ │                  │   _com_client=<communex.client.CommuneClient object at 0x7f8fafc18d60>    │ │
│ │                  )                                                                           │ │
│ │            ctx = <click.core.Context object at 0x7f8fafc0b820>                               │ │
│ │            key = 'key_name'                                                                  │ │
│ │ num_executions = 1                                                                           │ │
│ │  num_processes = None                                                                        │ │
│ │         params = {                                                                           │ │
│ │                  │   'block_number': 1269006,                                                │ │
│ │                  │   'nonce': 14229803247757581362,                                          │ │
│ │                  │   'work':                                                                 │ │
│ │                  b'\x00\x00\x0b\xa6"\xff\xad\x9bL\x8d<n,T\x80\xaa2_\xef\xa4\xbe\xad\xa2\x12… │ │
│ │                  │   'key': '5GVmdn1KUREHVvTgshoxkNMTM6ZV94EDh4MMuRhNEoyz6dyY'               │ │
│ │                  }                                                                           │ │
│ │   resolved_key = <Keypair (address=5GVmdn1KUREHVvTgshoxkNMTM6ZV94EDh4MMuRhNEoyz6dyY)>        │ │
│ │       solution = POWSolution(                                                                │ │
│ │                  │   nonce=14229803247757581362,                                             │ │
│ │                  │   block_number=1269006,                                                   │ │
│ │                  │                                                                           │ │
│ │                  seal=b'\x00\x00\x0b\xa6"\xff\xad\x9bL\x8d<n,T\x80\xaa2_\xef\xa4\xbe\xad\xa… │ │
│ │                  │                                                                           │ │
│ │                  block_hash='0xbb36d9fbdc19e70c0fa1a499a8e96f78b199497b6dd6cc7698d9f6d52324… │ │
│ │                  )                                                                           │ │
│ │    use_testnet = True                                                                        │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/communex/client.py:792 in compose_call                   │
│                                                                                                  │
│    789 │   │   │   if wait_for_finalization is None:                                             │
│    790 │   │   │   │   wait_for_finalization = self.wait_for_finalization                        │
│    791 │   │   │                                                                                 │
│ ❱  792 │   │   │   call = substrate.compose_call(  # type: ignore                                │
│    793 │   │   │   │   call_module=module, call_function=fn, call_params=params                  │
│    794 │   │   │   )                                                                             │
│    795 │   │   │   if sudo:                                                                      │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │                    fn = 'faucet'                                                             │ │
│ │                   key = '5GVmdn1KUREHVvTgshoxkNMTM6ZV94EDh4MMuRhNEoyz6dyY'                   │ │
│ │                module = 'FaucetModule'                                                       │ │
│ │                params = {                                                                    │ │
│ │                         │   'block_number': 1269006,                                         │ │
│ │                         │   'nonce': 14229803247757581362,                                   │ │
│ │                         │   'work':                                                          │ │
│ │                         b'\x00\x00\x0b\xa6"\xff\xad\x9bL\x8d<n,T\x80\xaa2_\xef\xa4\xbe\xad\… │ │
│ │                         │   'key': '5GVmdn1KUREHVvTgshoxkNMTM6ZV94EDh4MMuRhNEoyz6dyY'        │ │
│ │                         }                                                                    │ │
│ │                  self = <communex.client.CommuneClient object at 0x7f8fafc18d60>             │ │
│ │             substrate = <substrateinterface.base.SubstrateInterface object at                │ │
│ │                         0x7f8fafb1d4e0>                                                      │ │
│ │                  sudo = False                                                                │ │
│ │              unsigned = True                                                                 │ │
│ │ wait_for_finalization = False                                                                │ │
│ │    wait_for_inclusion = True                                                                 │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/substrateinterface/base.py:1407 in compose_call          │
│                                                                                                  │
│   1404 │   │   │   type_string='Call', metadata=self.metadata                                    │
│   1405 │   │   )                                                                                 │
│   1406 │   │                                                                                     │
│ ❱ 1407 │   │   call.encode({                                                                     │
│   1408 │   │   │   'call_module': call_module,                                                   │
│   1409 │   │   │   'call_function': call_function,                                               │
│   1410 │   │   │   'call_args': call_params                                                      │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │    block_hash = None                                                                         │ │
│ │          call = <GenericCall(value={'call_module': 'FaucetModule', 'call_function':          │ │
│ │                 'faucet', 'call_args': {'block_number': 1269006, 'nonce':                    │ │
│ │                 14229803247757581362, 'work':                                                │ │
│ │                 b'\x00\x00\x0b\xa6"\xff\xad\x9bL\x8d<n,T\x80\xaa2_\xef\xa4\xbe\xad\xa2\x12v… │ │
│ │                 'key': '5GVmdn1KUREHVvTgshoxkNMTM6ZV94EDh4MMuRhNEoyz6dyY'}})>                │ │
│ │ call_function = 'faucet'                                                                     │ │
│ │   call_module = 'FaucetModule'                                                               │ │
│ │   call_params = {                                                                            │ │
│ │                 │   'block_number': 1269006,                                                 │ │
│ │                 │   'nonce': 14229803247757581362,                                           │ │
│ │                 │   'work':                                                                  │ │
│ │                 b'\x00\x00\x0b\xa6"\xff\xad\x9bL\x8d<n,T\x80\xaa2_\xef\xa4\xbe\xad\xa2\x12v… │ │
│ │                 │   'key': '5GVmdn1KUREHVvTgshoxkNMTM6ZV94EDh4MMuRhNEoyz6dyY'                │ │
│ │                 }                                                                            │ │
│ │          self = <substrateinterface.base.SubstrateInterface object at 0x7f8fafb1d4e0>        │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/scalecodec/base.py:929 in encode                         │
│                                                                                                  │
│    926 │   │   │   self.value_serialized = value                                                 │
│    927 │   │   │   self.decoded = True                                                           │
│    928 │   │                                                                                     │
│ ❱  929 │   │   self.data = self.process_encode(self.value_serialized)                            │
│    930 │   │                                                                                     │
│    931 │   │   if self.value_object is None:                                                     │
│    932 │   │   │   self.value_object = self.value_serialized                                     │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │  self = <GenericCall(value={'call_module': 'FaucetModule', 'call_function': 'faucet',        │ │
│ │         'call_args': {'block_number': 1269006, 'nonce': 14229803247757581362, 'work':        │ │
│ │         b'\x00\x00\x0b\xa6"\xff\xad\x9bL\x8d<n,T\x80\xaa2_\xef\xa4\xbe\xad\xa2\x12v\xf9W\xb… │ │
│ │         'key': '5GVmdn1KUREHVvTgshoxkNMTM6ZV94EDh4MMuRhNEoyz6dyY'}})>                        │ │
│ │ value = {                                                                                    │ │
│ │         │   'call_module': 'FaucetModule',                                                   │ │
│ │         │   'call_function': 'faucet',                                                       │ │
│ │         │   'call_args': {                                                                   │ │
│ │         │   │   'block_number': 1269006,                                                     │ │
│ │         │   │   'nonce': 14229803247757581362,                                               │ │
│ │         │   │   'work':                                                                      │ │
│ │         b'\x00\x00\x0b\xa6"\xff\xad\x9bL\x8d<n,T\x80\xaa2_\xef\xa4\xbe\xad\xa2\x12v\xf9W\xb… │ │
│ │         │   │   'key': '5GVmdn1KUREHVvTgshoxkNMTM6ZV94EDh4MMuRhNEoyz6dyY'                    │ │
│ │         │   }                                                                                │ │
│ │         }                                                                                    │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/scalecodec/types.py:1647 in process_encode               │
│                                                                                                  │
│   1644 │   │   │   │   raise ValueError('No call module and function specified')                 │
│   1645 │   │   │                                                                                 │
│   1646 │   │   │   if not self.call_module:                                                      │
│ ❱ 1647 │   │   │   │   raise ValueError(f"Pallet '{value['call_module']}' not found")            │
│   1648 │   │   │                                                                                 │
│   1649 │   │   │   data = ScaleBytes(self.call_module['index'].get_used_bytes())                 │
│   1650                                                                                           │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │  self = <GenericCall(value={'call_module': 'FaucetModule', 'call_function': 'faucet',        │ │
│ │         'call_args': {'block_number': 1269006, 'nonce': 14229803247757581362, 'work':        │ │
│ │         b'\x00\x00\x0b\xa6"\xff\xad\x9bL\x8d<n,T\x80\xaa2_\xef\xa4\xbe\xad\xa2\x12v\xf9W\xb… │ │
│ │         'key': '5GVmdn1KUREHVvTgshoxkNMTM6ZV94EDh4MMuRhNEoyz6dyY'}})>                        │ │
│ │ value = {                                                                                    │ │
│ │         │   'call_module': 'FaucetModule',                                                   │ │
│ │         │   'call_function': 'faucet',                                                       │ │
│ │         │   'call_args': {                                                                   │ │
│ │         │   │   'block_number': 1269006,                                                     │ │
│ │         │   │   'nonce': 14229803247757581362,                                               │ │
│ │         │   │   'work':                                                                      │ │
│ │         b'\x00\x00\x0b\xa6"\xff\xad\x9bL\x8d<n,T\x80\xaa2_\xef\xa4\xbe\xad\xa2\x12v\xf9W\xb… │ │
│ │         │   │   'key': '5GVmdn1KUREHVvTgshoxkNMTM6ZV94EDh4MMuRhNEoyz6dyY'                    │ │
│ │         │   }                                                                                │ │
│ │         }                                                                                    │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: Pallet 'FaucetModule' not found

**Comment by Supremesource** [comment]
Resolved, compiled with faucet flag
